torch:
- chunk
- split
- stack
- matmul
- lobpcg
- abs
- absolute
- acos
- acosh
- adaptive_avg_pool1d
- adaptive_max_pool1d
- add
- addbmm
- addcdiv
- addcmul
- addmm
- addmv
- addr
- affine_grid_generator
- all
- allclose
- alpha_dropout
- amax
- amin
- angle
- any
- arccos
- arccosh
- arcsin
- arcsinh
- arctan
- arctanh
- argmax
- argmin
- argsort
- asin
- asinh
- atan
- atan2
- atanh
- atleast_1d
- atleast_2d
- atleast_3d
- avg_pool1d
- baddbmm
- batch_norm
- batch_norm_backward_elemt
- batch_norm_backward_reduce
- batch_norm_elemt
- batch_norm_gather_stats
- batch_norm_gather_stats_with_counts
- batch_norm_stats
- batch_norm_update_stats
- bernoulli
- bilinear
- binary_cross_entropy_with_logits
- bincount
- binomial
- bitwise_and
- bitwise_not
- bitwise_or
- bitwise_xor
- block_diag
- bmm
- broadcast_tensors
- bucketize
- cartesian_prod
- cat
- cdist
- ceil
- celu
- chain_matmul
- channel_shuffle
- cholesky
- cholesky_inverse
- cholesky_solve
- choose_qparams_optimized
- clamp
- clamp_max
- clamp_min
- clip
- clone
- combinations
- complex
- conj
- constant_pad_nd
- conv1d
- conv2d
- conv3d
- conv_tbc
- conv_transpose1d
- conv_transpose2d
- conv_transpose3d
- convolution
- cos
- cosh
- cosine_embedding_loss
- cosine_similarity
- count_nonzero
- cross
- ctc_loss
- cummax
- cummin
- cumprod
- cumsum
- deg2rad
- dequantize
- det
- detach
- diag
- diag_embed
- diagflat
- diagonal
- digamma
- dist
- div
- divide
- dot
- dropout
- dsmm
- dstack
- eig
- einsum
- embedding
- embedding_bag
- empty_like
- eq
- equal
- erf
- erfc
- erfinv
- exp
- exp2
- expm1
- fake_quantize_per_channel_affine
- fake_quantize_per_tensor_affine
- fbgemm_linear_fp16_weight
- fbgemm_linear_fp16_weight_fp32_activation
- fbgemm_linear_int8_weight
- fbgemm_linear_int8_weight_fp32_activation
- fbgemm_linear_quantize_weight
- fbgemm_pack_gemm_matrix_fp16
- fbgemm_pack_quantized_matrix
- feature_alpha_dropout
- feature_dropout
- fft
- fix
- flatten
- flip
- fliplr
- flipud
- floor
- floor_divide
- fmod
- frac
- frobenius_norm
- full_like
- gather
- gcd
- ge
- geqrf
- ger
- greater
- greater_equal
- grid_sampler
- grid_sampler_2d
- grid_sampler_3d
- group_norm
- gru
- gru_cell
- gt
- hardshrink
- heaviside
- hinge_embedding_loss
- histc
- hsmm
- hspmm
- hstack
- hypot
- i0
- ifft
- imag
- index_add
- index_copy
- index_fill
- index_put
- index_select
- instance_norm
- int_repr
- inverse
- irfft
- is_complex
- is_distributed
- is_floating_point
- is_nonzero
- is_same_size
- is_signed
- isclose
- isfinite
- isinf
- isnan
- isneginf
- isposinf
- isreal
- istft
- kl_div
- kthvalue
- layer_norm
- lcm
- le
- lerp
- less
- less_equal
- lgamma
- log
- log10
- log1p
- log2
- log_softmax
- logaddexp
- logaddexp2
- logcumsumexp
- logdet
- logical_and
- logical_not
- logical_or
- logical_xor
- logit
- logsumexp
- lstm
- lstm_cell
- lstsq
- lt
- lu_solve
- margin_ranking_loss
- masked_fill
- masked_scatter
- masked_select
- matrix_exp
- matrix_power
- matrix_rank
- max
- max_pool1d
- max_pool1d_with_indices
- max_pool2d
- max_pool3d
- maximum
- mean
- median
- meshgrid
- min
- minimum
- miopen_batch_norm
- miopen_convolution
- miopen_convolution_transpose
- miopen_depthwise_convolution
- miopen_rnn
- mm
- mode
- movedim
- mul
- multinomial
- multiply
- mv
- mvlgamma
- nanquantile
- nansum
- narrow
- native_batch_norm
- native_group_norm
- native_layer_norm
- native_norm
- ne
- neg
- negative
- nextafter
- nonzero
- norm
- norm_except_dim
- not_equal
- nuclear_norm
- numel
- ones_like
- orgqr
- ormqr
- outer
- pairwise_distance
- pdist
- pinverse
- pixel_shuffle
- poisson
- poisson_nll_loss
- polar
- polygamma
- pow
- prelu
- prod
- q_per_channel_axis
- q_per_channel_scales
- q_per_channel_zero_points
- q_scale
- q_zero_point
- qr
- quantile
- quantize_per_channel
- quantize_per_tensor
- quantized_batch_norm
- quantized_gru_cell
- quantized_lstm_cell
- quantized_max_pool1d
- quantized_max_pool2d
- quantized_rnn_relu_cell
- quantized_rnn_tanh_cell
- rad2deg
- rand_like
- randint_like
- randn_like
- real
- reciprocal
- relu
- remainder
- renorm
- repeat_interleave
- reshape
- rfft
- rnn_relu
- rnn_relu_cell
- rnn_tanh
- rnn_tanh_cell
- roll
- rot90
- round
- rrelu
- rsqrt
- rsub
- saddmm
- scatter
- scatter_add
- searchsorted
- select
- selu
- sgn
- sigmoid
- sign
- signbit
- sin
- sinh
- slogdet
- smm
- softmax
- solve
- sort
- split_with_sizes
- spmm
- sqrt
- square
- squeeze
- sspaddmm
- std
- std_mean
- stft
- sub
- subtract
- sum
- svd
- symeig
- t
- take
- tan
- tanh
- tensordot
- threshold
- topk
- trace
- transpose
- trapz
- triangular_solve
- tril
- triplet_margin_loss
- triu
- true_divide
- trunc
- unbind
- unique_consecutive
- unsafe_chunk
- unsafe_split
- unsafe_split_with_sizes
- unsqueeze
- var
- var_mean
- vdot
- view_as_complex
- view_as_real
- vstack
- where
- zeros_like
torch.Tensor:
# Manually added
- __neg__
- __pow__
# Automatically added
- abs
- __add__
- __and__
- __array__
- __array_wrap__
- __bool__
- __complex__
- __contains__
- __deepcopy__
- __div__
- eq
- __float__
- __floordiv__
- __format__
- ge
- __getitem__
- gt
- __hash__
- __iadd__
- __iand__
- __idiv__
- __ifloordiv__
- __ilshift__
- __imul__
- __index__
- __int__
- __invert__
- __ior__
- __ipow__
- __irshift__
- __isub__
- __iter__
- __ixor__
- le
- __len__
- __long__
- __lshift__
- lt
- __matmul__
- __mod__
- __mul__
- ne
- neg
- __nonzero__
- __or__
- pow
- __radd__
- __rdiv__
- __reduce_ex__
- __repr__
- __reversed__
- __rfloordiv__
- __rmul__
- __rpow__
- __rshift__
- __rsub__
- __setitem__
- __setstate__
- __sub__
- __truediv__
- __xor__
- _coalesced_
- _dimI
- _dimV
- _indices
- _is_view
- _nnz
- _update_names
- _values
- abs_
- absolute
- absolute_
- acos
- acos_
- acosh
- acosh_
- add
- add_
- addbmm
- addbmm_
- addcdiv
- addcdiv_
- addcmul
- addcmul_
- addmm
- addmm_
- addmv
- addmv_
- addr
- addr_
- align_as
- align_to
- all
- allclose
- amax
- amin
- angle
- any
- apply_
- arccos
- arccos_
- arccosh
- arccosh_
- arcsin
- arcsin_
- arcsinh
- arcsinh_
- arctan
- arctan_
- arctanh
- arctanh_
- argmax
- argmin
- argsort
- as_strided
- as_strided_
- asin
- asin_
- asinh
- asinh_
- atan
- atan2
- atan2_
- atan_
- atanh
- atanh_
- backward
- baddbmm
- baddbmm_
- bernoulli
- bernoulli_
- bfloat16
- bincount
- bitwise_and
- bitwise_and_
- bitwise_not
- bitwise_not_
- bitwise_or
- bitwise_or_
- bitwise_xor
- bitwise_xor_
- bmm
- bool
- byte
- cauchy_
- ceil
- ceil_
- char
- cholesky
- cholesky_inverse
- cholesky_solve
- chunk
- clamp
- clamp_
- clamp_max
- clamp_max_
- clamp_min
- clamp_min_
- clip
- clip_
- clone
- coalesce
- conj
- contiguous
- copy_
- cos
- cos_
- cosh
- cosh_
- count_nonzero
- cpu
- cross
- cuda
- cummax
- cummin
- cumprod
- cumsum
- data_ptr
- deg2rad
- deg2rad_
- dense_dim
- dequantize
- det
- detach
- detach_
- diag
- diag_embed
- diagflat
- diagonal
- digamma
- digamma_
- dim
- dist
- div
- div_
- divide
- divide_
- dot
- double
- eig
- element_size
- eq_
- equal
- erf
- erf_
- erfc
- erfc_
- erfinv
- erfinv_
- exp
- exp2
- exp2_
- exp_
- expand
- expand_as
- expm1
- expm1_
- exponential_
- fft
- fill_
- fill_diagonal_
- fix
- fix_
- flatten
- flip
- fliplr
- flipud
- float
- floor
- floor_
- floor_divide
- floor_divide_
- fmod
- fmod_
- frac
- frac_
- gather
- gcd
- gcd_
- ge_
- geometric_
- geqrf
- ger
- get_device
- greater
- greater_
- greater_equal
- greater_equal_
- gt_
- half
- hardshrink
- has_names
- heaviside
- heaviside_
- histc
- hypot
- hypot_
- i0
- i0_
- ifft
- index_add
- index_add_
- index_copy
- index_copy_
- index_fill
- index_fill_
- index_put
- index_put_
- index_select
- indices
- int
- int_repr
- inverse
- irfft
- is_coalesced
- is_complex
- is_contiguous
- is_distributed
- is_floating_point
- is_nonzero
- is_pinned
- is_same_size
- is_set_to
- is_shared
- is_signed
- isclose
- isfinite
- isinf
- isnan
- isneginf
- isposinf
- isreal
- istft
- item
- kthvalue
- lcm
- lcm_
- le_
- lerp
- lerp_
- less
- less_
- less_equal
- less_equal_
- lgamma
- lgamma_
- log
- log10
- log10_
- log1p
- log1p_
- log2
- log2_
- log_
- log_normal_
- log_softmax
- logaddexp
- logaddexp2
- logcumsumexp
- logdet
- logical_and
- logical_and_
- logical_not
- logical_not_
- logical_or
- logical_or_
- logical_xor
- logical_xor_
- logit
- logit_
- logsumexp
- long
- lstsq
- lt_
- lu
- lu_solve
- map2_
- map_
- masked_fill
- masked_fill_
- masked_scatter
- masked_scatter_
- masked_select
- matmul
- matrix_exp
- matrix_power
- max
- maximum
- mean
- median
- min
- minimum
- mm
- mode
- movedim
- mul
- mul_
- multinomial
- multiply
- multiply_
- mv
- mvlgamma
- mvlgamma_
- nanquantile
- nansum
- narrow
- narrow_copy
- ndimension
- ne_
- neg_
- negative
- negative_
- nelement
- nextafter
- nextafter_
- nonzero
- norm
- normal_
- not_equal
- not_equal_
- numel
- numpy
- orgqr
- ormqr
- outer
- permute
- pin_memory
- pinverse
- polygamma
- polygamma_
- pow_
- prelu
- prod
- put_
- q_per_channel_axis
- q_per_channel_scales
- q_per_channel_zero_points
- q_scale
- q_zero_point
- qr
- qscheme
- quantile
- rad2deg
- rad2deg_
- random_
- reciprocal
- reciprocal_
- record_stream
- refine_names
- register_hook
- relu
- relu_
- remainder
- remainder_
- rename
- rename_
- renorm
- renorm_
- repeat
- repeat_interleave
- requires_grad_
- reshape
- reshape_as
- resize
- resize_
- resize_as
- resize_as_
- retain_grad
- rfft
- roll
- rot90
- round
- round_
- rsqrt
- rsqrt_
- scatter
- scatter_
- scatter_add
- scatter_add_
- select
- set_
- sgn
- sgn_
- share_memory_
- short
- sigmoid
- sigmoid_
- sign
- sign_
- signbit
- sin
- sin_
- sinh
- sinh_
- size
- slogdet
- smm
- softmax
- solve
- sort
- sparse_dim
- sparse_mask
- sparse_resize_
- sparse_resize_and_clear_
- split
- split_with_sizes
- sqrt
- sqrt_
- square
- square_
- squeeze
- squeeze_
- sspaddmm
- std
- stft
- storage
- storage_offset
- storage_type
- sub
- sub_
- subtract
- subtract_
- sum
- sum_to_size
- svd
- symeig
- t
- t_
- take
- tan
- tan_
- tanh
- tanh_
- to
- to_dense
- to_mkldnn
- to_sparse
- tolist
- topk
- trace
- transpose
- transpose_
- triangular_solve
- tril
- tril_
- triu
- triu_
- true_divide
- true_divide_
- trunc
- trunc_
- type
- type_as
- unbind
- unfold
- uniform_
- unique
- unique_consecutive
- unsafe_chunk
- unsafe_split
- unsafe_split_with_sizes
- unsqueeze
- unsqueeze_
- values
- var
- vdot
- view
- view_as
- where
- zero_
torch.functional:
- atleast_1d
- atleast_2d
- atleast_3d
- broadcast_tensors
- cartesian_prod
- block_diag
- cdist
- chain_matmul
- einsum
- istft
- lu
- lu_unpack
- norm
- meshgrid
- pca_lowrank
- split
- stft
- svd_lowrank
- tensordot
- unique
- unique_consecutive
torch.nn.functional:
# Manually added
- pad
# Automatically added
- adaptive_avg_pool1d
- adaptive_avg_pool2d
- adaptive_avg_pool3d
- adaptive_max_pool1d
- adaptive_max_pool1d_with_indices
- adaptive_max_pool2d
- adaptive_max_pool2d_with_indices
- adaptive_max_pool3d
- adaptive_max_pool3d_with_indices
- affine_grid
- alpha_dropout
- avg_pool1d
- avg_pool2d
- avg_pool3d
- batch_norm
- bilinear
- binary_cross_entropy
- binary_cross_entropy_with_logits
- celu
- channel_shuffle
- conv1d
- conv2d
- conv3d
- conv_tbc
- conv_transpose1d
- conv_transpose2d
- conv_transpose3d
- cosine_embedding_loss
- cosine_similarity
- cross_entropy
- ctc_loss
- dropout
- dropout2d
- dropout3d
- elu
- embedding
- embedding_bag
- feature_alpha_dropout
- fold
- fractional_max_pool2d
- fractional_max_pool2d_with_indices
- fractional_max_pool3d
- fractional_max_pool3d_with_indices
- gelu
- glu
- grid_sample
- group_norm
- gumbel_softmax
- hardshrink
- hardswish
- hardtanh
- hardsigmoid
- hinge_embedding_loss
- instance_norm
- interpolate
- kl_div
- l1_loss
- layer_norm
- leaky_relu
- linear
- local_response_norm
- log_softmax
- log_sigmoid
- lp_pool1d
- lp_pool2d
- margin_ranking_loss
- max_pool1d
- max_pool1d_with_indices
- max_pool2d
- max_pool2d_with_indices
- max_pool3d
- max_pool3d_with_indices
- max_unpool1d
- max_unpool2d
- max_unpool3d
- mse_loss
- multi_head_attention_forward
- multi_margin_loss
- multilabel_margin_loss
- multilabel_soft_margin_loss
- nll_loss
- normalize
- one_hot
- _pad
- pairwise_distance
- pdist
- pixel_shuffle
- poisson_nll_loss
- prelu
- relu
- relu6
- rrelu
- selu
- silu
- smooth_l1_loss
- soft_margin_loss
- softmax
- softmin
- softplus
- softshrink
- softsign
- tanhshrink
- _threshold
- triplet_margin_loss
- triplet_margin_with_distance_loss
- unfold
torchvision.ops:
- _new_empty_tensor
- box_iou
- deform_conv2d
- nms
- ps_roi_align
- ps_roi_pool
- roi_align
- roi_pool
