torch:
- ByteTensor
- CharTensor
- DoubleTensor
- FloatTensor
- IntTensor
- LongTensor
- ShortTensor
- HalfTensor
- BoolTensor
- BFloat16Tensor
- arange
- as_strided
- as_tensor
- asarray
- bartlett_window
- blackman_window
- empty
- empty_strided
- eye
- from_file
- full
- hamming_window
- hann_window
- kaiser_window
- linspace
- logspace
- normal
- ones
- rand
- randint
- randn
- randperm
- range
- sparse_coo_tensor
- sparse_csr_tensor
- tensor
- tril_indices
- triu_indices
- vander
- zeros
